language: node_js
node_js:
  - 'stable'
script:
  - npm test
  - npm run build-server
  - cd ./frontend
  - npm install
  - npm run test-ci
  - npm run build-client
  - cd ..
after_success:
  - node node_modules/lighthouse-ci/runlighthouse.js https://youtube-mixtape-v2-staging.herokuapp.com
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $heroku_api_key
  app:
    master: youtube-mixtape-v2
    v2-development-03: youtube-mixtape-v2-staging
  run:
    - restart